2023-11-07 22:02:30,922 INFO    MainThread:2665 [wandb_setup.py:_flush():76] Current SDK version is 0.15.8
2023-11-07 22:02:30,923 INFO    MainThread:2665 [wandb_setup.py:_flush():76] Configure stats pid to 2665
2023-11-07 22:02:30,923 INFO    MainThread:2665 [wandb_setup.py:_flush():76] Loading settings from /Users/junhyeonbae/.config/wandb/settings
2023-11-07 22:02:30,923 INFO    MainThread:2665 [wandb_setup.py:_flush():76] Loading settings from /Users/junhyeonbae/PycharmProjects/MAgent2_hetero/wandb/settings
2023-11-07 22:02:30,923 INFO    MainThread:2665 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-11-07 22:02:30,923 INFO    MainThread:2665 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-11-07 22:02:30,923 INFO    MainThread:2665 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'test.py', 'program': '/Users/junhyeonbae/PycharmProjects/MAgent2_hetero/test.py'}
2023-11-07 22:02:30,924 INFO    MainThread:2665 [wandb_init.py:_log_setup():507] Logging user logs to /Users/junhyeonbae/PycharmProjects/MAgent2_hetero/wandb/run-20231107_220230-cf129k0m/logs/debug.log
2023-11-07 22:02:30,924 INFO    MainThread:2665 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/junhyeonbae/PycharmProjects/MAgent2_hetero/wandb/run-20231107_220230-cf129k0m/logs/debug-internal.log
2023-11-07 22:02:30,924 INFO    MainThread:2665 [wandb_init.py:init():547] calling init triggers
2023-11-07 22:02:30,924 INFO    MainThread:2665 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-11-07 22:02:30,924 INFO    MainThread:2665 [wandb_init.py:init():596] starting backend
2023-11-07 22:02:30,924 INFO    MainThread:2665 [wandb_init.py:init():600] setting up manager
2023-11-07 22:02:30,932 INFO    MainThread:2665 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-11-07 22:02:30,933 INFO    MainThread:2665 [wandb_init.py:init():606] backend started and connected
2023-11-07 22:02:30,942 INFO    MainThread:2665 [wandb_init.py:init():697] updated telemetry
2023-11-07 22:02:30,967 INFO    MainThread:2665 [wandb_init.py:init():730] communicating run to backend with 60.0 second timeout
2023-11-07 22:02:31,561 ERROR   MainThread:2665 [wandb_init.py:init():756] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-11-07 22:02:31,654 ERROR   MainThread:2665 [wandb_init.py:init():1165] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/Users/junhyeonbae/anaconda3/envs/MAgent2_hetero/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1147, in init
    run = wi.init()
  File "/Users/junhyeonbae/anaconda3/envs/MAgent2_hetero/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 762, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-11-07 22:02:32,661 WARNING MsgRouterThr:2665 [router.py:message_loop():77] message_loop has been closed
