2023-11-07 21:10:45,037 INFO    MainThread:2321 [wandb_setup.py:_flush():76] Current SDK version is 0.15.8
2023-11-07 21:10:45,038 INFO    MainThread:2321 [wandb_setup.py:_flush():76] Configure stats pid to 2321
2023-11-07 21:10:45,038 INFO    MainThread:2321 [wandb_setup.py:_flush():76] Loading settings from /Users/junhyeonbae/.config/wandb/settings
2023-11-07 21:10:45,038 INFO    MainThread:2321 [wandb_setup.py:_flush():76] Loading settings from /Users/junhyeonbae/PycharmProjects/MAgent2_hetero/wandb/settings
2023-11-07 21:10:45,038 INFO    MainThread:2321 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-11-07 21:10:45,038 INFO    MainThread:2321 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-11-07 21:10:45,038 INFO    MainThread:2321 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'test.py', 'program': '/Users/junhyeonbae/PycharmProjects/MAgent2_hetero/test.py'}
2023-11-07 21:10:45,038 INFO    MainThread:2321 [wandb_init.py:_log_setup():507] Logging user logs to /Users/junhyeonbae/PycharmProjects/MAgent2_hetero/wandb/run-20231107_211045-u3jyn4v6/logs/debug.log
2023-11-07 21:10:45,038 INFO    MainThread:2321 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/junhyeonbae/PycharmProjects/MAgent2_hetero/wandb/run-20231107_211045-u3jyn4v6/logs/debug-internal.log
2023-11-07 21:10:45,038 INFO    MainThread:2321 [wandb_init.py:init():547] calling init triggers
2023-11-07 21:10:45,038 INFO    MainThread:2321 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-11-07 21:10:45,039 INFO    MainThread:2321 [wandb_init.py:init():596] starting backend
2023-11-07 21:10:45,039 INFO    MainThread:2321 [wandb_init.py:init():600] setting up manager
2023-11-07 21:10:45,044 INFO    MainThread:2321 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-11-07 21:10:45,046 INFO    MainThread:2321 [wandb_init.py:init():606] backend started and connected
2023-11-07 21:10:45,055 INFO    MainThread:2321 [wandb_init.py:init():697] updated telemetry
2023-11-07 21:10:45,072 INFO    MainThread:2321 [wandb_init.py:init():730] communicating run to backend with 60.0 second timeout
2023-11-07 21:10:45,606 ERROR   MainThread:2321 [wandb_init.py:init():756] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-11-07 21:10:45,685 ERROR   MainThread:2321 [wandb_init.py:init():1165] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/Users/junhyeonbae/anaconda3/envs/MAgent2_hetero/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1147, in init
    run = wi.init()
  File "/Users/junhyeonbae/anaconda3/envs/MAgent2_hetero/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 762, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-11-07 21:10:46,710 WARNING MsgRouterThr:2321 [router.py:message_loop():77] message_loop has been closed
